name: Yarn Target Determinator
description: Determine a list of Yarn 2 workspaces to test using a list of changed files.

branding:
  icon: target
  color: red

inputs:
  files:
    description: Array of all changed files to validate, encoded as a JSON array
    required: true

outputs:
  targets:
    description: The list of Yarn workspaces to test, encoded as a JSON array

runs:
  using: node12
  main: dist/index.js
